config/routes.rb
Xanbook::Application.routes.draw do


  get 'home', to: 'basic#home', as: :home

  get 'about', to: 'basic#about', as: :about

  get 'welcome', to: 'basic#welcome', as: :welcome

  get 'feed', to: 'statuses#index', as: :feed

  get 'profiles/:id', to: 'profiles#show'

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'sign_in', to: 'devise/sessions#new', as: :sign_in
    delete 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
  end

  root to: 'basic#home'

  resources :statuses

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true,
                      length: { minimum: 3 }

  validates :user_id, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true
  
  validates :last_name, presence: true

  validates :profile_name, presence: true,
                           uniqueness: true,
                           format: {
                              with: /^[a-zA-Z0-9_-]+$/,
                              message: "Must be formatted correctly."
                           }

  has_many :statuses

  def full_name
    "#{first_name} #{last_name}"
  end

  def gravatar_url
    "http://gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email.downcase.strip)}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/basic_controller.rb
class BasicController < ApplicationController
  def home
  end

  def about
  end

  def welcome
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :update, :edit]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class type
    case type
    when :alert
      "alert-error"
    when :notice
      "alert-success"
    else
      ""
    end
  end

end

app/helpers/basic_helper.rb
module BasicHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/basic/about.html.erb
<h1>Basic#about</h1>
<p>Find me in app/views/basic/about.html.erb</p>

app/views/basic/home.html.erb
  <div class='row'>
    <div class='span12'>
      <div class='hero-unit'>
        <h1 class="text-center">Welcome to Xanbook!</h1>
        <p class="lead text-center">A simple Rails app that lets you post your status and track the status of other users.</p>
        <p class="text-center">
        <div class="btn-group">
        
          <%= link_to 'Sign In', sign_in_path, class: 'btn btn-large btn-success'%>
          <%= link_to 'Sign Up', register_path, class: 'btn btn-large btn-primary'%>
        </div>
        </p>
      </div>
    </div>
  </div>

<h2>Featuring...</h2>
<div class='row'>
  <div class='span4'>
    <h3>Bootstrap Stylings</h3>
    <p>Xanbook is made prettier using Bootstrap 2.3.2.</p>
  </div>
  <div class='span4'>
    <h3>Simple Form & Devise</h3>
    <p>Forms are generated using the Simple Form gem for simpler and cleaner form coding. Also the Devise gem is used as an Authorization solution.</p>
  </div>
  <div class='span4'>
    <h3>Test Driven Development</h3>
    <p>Xanbook was built starting from tests written using Test::Unit.</p>
  </div>
</div>

app/views/basic/welcome.html.erb
<h1>Basic#welcome</h1>
<p>Find me in app/views/basic/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xanbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Xanbook', root_path, class: 'brand' %>
          <ul class="nav"> 
            <li><%= link_to 'Feed', feed_path  %></li>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
              <li><%= link_to "Sign Out", sign_out_path, method: :delete %>
            <% else %>
              <li><%= link_to "Sign In", sign_in_path %></li>
              <li><%= link_to "Register", register_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

  <div class='container'>

    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= message %>
      </div>
    <% end %>
    
    <%= yield %>

    <div class="footer">
      <p>Xander Miller 2014</p>
    </div>
  </div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  <h1><%= @user.full_name %> <small><%= @user.email %></small></h1>

  <%= render @statuses %>
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: 'form-horizontal' }) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/_status.html.erb
<div class='status'>
  <div class='row'>
    <div class='span1'>
      <%= image_tag status.user.gravatar_url, alt: 'Gravatar' %>
    </div>
    <div class='span7'>
      <strong><%= status.user.full_name %></strong>
      <p><%= status.content %></p>
      <div class='meta'>
        <%= link_to "#{time_ago_in_words(status.created_at)} ago", status %>
        <span class='admin'>
           | <%= link_to 'Edit', edit_status_path(status) %> |
          <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All Statuses</h1>
</div>

<%= link_to 'New Status', new_status_path, class: 'btn btn-primary' %>

<%= render @statuses %>



<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>